### PR TITLE
events proposal

### PR DESCRIPTION
**Pull request by tedpatrick**
This events proposal is research on all potential event options for PyScript.

Goals:

1. Align with modern use of events using addEventListener/removeEventListener and DOM Events
2. Support the use of custom events to capture PyScript lifecycle events
3. Keep it as simple as possible to make Python work closely with events.

### CODE REVIEW

**Comment by pauleveritt** [comment]
Is it correct that `@handler` in the Python code references a symbol `handler` which doesn't exist in Python, it comes from the JS side? (Meaning, IDEs can't help on completion or argument passing.)

**Comment by JeffersGlass** [comment]
@pauleveritt i believe it refers to the [handler function defined here](https://github.com/pyscript/research/blob/fc4217ea07f88354b596da3371255d270e58ad5c/proposals/wip_events/onevent.html#L53), used as a decorator. My understanding is that this Python code would be integrated into PyScript.py (or similar), but for illustration is being shown just within a py-script tag.

**Comment by tedpatrick** [comment]
Note: I am not married to the names.

@handler is just a decorator that exposes a python function to js and optionally subscribes via DOM Events addEventListener https://github.com/pyscript/research/blob/main/proposals/wip_events/onevent.html#L53-L71

**Comment by pauleveritt** [comment]
Sorry, I typed too fast. When I first read it, it appeared that usages of `@handler` where getting it without an import. The example has kind of a comment that tries to layout which is on which side of the fence, so to speak.

As long as usages of it have a proper import, all good. (As you noted @JeffersGlass )

**Pull request merged**
